name: video_collector_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python==3.9.23
  - ipykernel==6.30.1
  - pip:
      - absl-py==2.3.1
      - appnope==0.1.4
      - asttokens==3.0.0
      - attrs==25.4.0
      - cffi==2.0.0
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - importlib_metadata==8.7.0
      - importlib_resources==6.5.2
      - ipykernel==6.30.1
      - ipython==8.18.1
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jupyter_client==8.6.3
      - jupyter_core==5.8.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mediapipe==0.10.21
      - ml_dtypes==0.5.3
      - nest_asyncio==1.6.0
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.12.0.88
      - opt_einsum==3.4.0
      - packaging==25.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - pip==25.2
      - pipdeptree==2.28.0
      - platformdirs==4.3.8
      - prompt_toolkit==3.0.51
      - protobuf==4.25.8
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - pycparser==2.23
      - Pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyzmq==27.0.2
      - scipy==1.13.1
      - sentencepiece==0.2.1
      - setuptools==80.9.0
      - six==1.17.0
      - sounddevice==0.5.3
      - stack_data==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing_extensions==4.14.1
      - wcwidth==0.2.13
      - wheel==0.45.1
      - zipp==3.23.0